version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ligence
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hw
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: generator
    command: bash -c "uvicorn app.generator:app --host 0.0.0.0 --port 8000"
    environment:
      - ROLE=generator
    volumes:
      - ./app:/app/app
      - ./fs:/app/fs
    depends_on:
      - postgres
      - redis
      - worker
    ports:
      - "8000:8000"
    env_file:
      - .env

  verifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verifier
    command: bash -c "uvicorn app.verifier:app --host 0.0.0.0 --port 8001"
    environment:
      - ROLE=verifier
    volumes:
      - ./app:/app/app
      - ./fs:/app/fs
    depends_on:
      - postgres
      - redis
      - worker
    ports:
      - "8001:8001"
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    command: python app/worker.py
    volumes:
      - ./app:/app/app
      - ./fs:/app/fs
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - generator
      - verifier

volumes:
  pgdata: